image: tiangolo/docker-with-compose

stages:
  - build
  - deploy

build-cod1-swarm:
  stage: build
  tags:
    - cod1
  script:
    - docker-compose build
  only:
    - master

deploy-cod1-swarm:
  stage: deploy
  variables:
    HOST: "courses.science.psu.edu"
  tags:
    - cod1
  script:
    - pwd
    - ls -la
    - docker stack deploy -c docker-compose.yml --resolve-image always practice-questions
  only:
    - master